# Generated by Django 3.1.4 on 2020-12-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201229_0654'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['deleted_at'], name='posts_deleted_09f519_idx'),
        ),
    ]
