version: "3.9"
   
services:
  web:
    build: .
    command: python manage.py runserver_plus 0.0.0.0:8000
    volumes:
      - .:/workspace/django_drf_tutorials
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - mysql
      - redis
  mysql:
    restart: always
    image: mysql:5.7
    container_name: django_drf_tutorials-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=django_drf_tutorials
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
    ports:
      - "3306:3306"
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./volumes/data/mysql:/var/lib/mysql/
  redis:
    restart: always
    container_name: django_drf_tutorials-redis
    image: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - './volumes/data/redis:/data'