@BASE_URL = http://127.0.0.1:8000

###
# register
POST {{BASE_URL}}/api/users/register
Content-Type: application/json

{
    "email": "sjahn2@ktown4u.com",
    "name": "sjahn",
    "password": "rewq1234"
}

###
# @name login
POST {{BASE_URL}}/api/users/login
Content-Type: application/json

{
    "email": "sjahn@ktown4u.com",
    "password": "rewq1234"
}

###
@token = {{login.response.body.user.token}}

###
# list
GET {{BASE_URL}}/api/posts
?page=1
Content-Type: application/json
Authorization: Bearer {{token}}


###
# create
POST {{BASE_URL}}/api/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "hello user 2 article",
    "body": "test contents"
}

###
# show
GET {{BASE_URL}}/api/posts/34
Content-Type: application/json
Authorization: Bearer {{token}}

###
# update
PUT {{BASE_URL}}/api/posts/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "modify article 444",
    "body": "hello wowowowowo"
}

###
# delete
DELETE {{BASE_URL}}/api/posts/6
Content-Type: application/json
Authorization: Bearer {{token}}


###
# comment.create
POST {{BASE_URL}}/api/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "commentable_id": 34,
    "commentable_type": "posts",
    "body": "test comments"
}


### 
# reference.list
GET {{BASE_URL}}/api/references
?name=user_level
Content-Type: application/json
Authorization: Bearer {{token}}


### 
# reference.create
POST {{BASE_URL}}/api/references
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "user_level",
    "key": "manager",
    "value": "500",
    "order": 500
}