@BASE_URL = http://127.0.0.1:8000

###
# register
POST {{BASE_URL}}/api/auth/register
Content-Type: application/json

{
    "email": "sjahn@ktown4u.com",
    "name": "sjahn",
    "password": "rewq1234"
}


###
# @name login
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
    "email": "admin@abc.com",
    "password": "rewq1234"
}

###
@token = {{login.response.body.result.token}}

###
GET {{BASE_URL}}/api/auth/me
Content-Type: application/json
Authorization: Bearer {{token}}



###
# aes crypto encrypt
POST {{BASE_URL}}/api/examples/aescrypto/encrypt
Content-Type: application/json

{
    "word": "hello world"
}

###
# aes crypto decrypt
POST {{BASE_URL}}/api/examples/aescrypto/decrypt
Content-Type: application/json

{
    "encrypt": "DiDp25udVdvrSDbFWWMLpMRClLISmQvXo+xMrSOmq7M="
}

###
# redis set
POST {{BASE_URL}}/api/examples/redis
Content-Type: application/json


###
# raw articles list
GET {{BASE_URL}}/api/examples/articles
Content-Type: application/json


###
# raw articles detail
GET {{BASE_URL}}/api/examples/articles/3
Content-Type: application/json


###
# posts.list
GET {{BASE_URL}}/api/posts
Content-Type: application/json
Authorization: Bearer {{token}}


###
# posts.create
POST {{BASE_URL}}/api/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "hello article",
    "body": "im writer"
}

###
# posts.show
GET {{BASE_URL}}/api/posts/1
Content-Type: application/json
Authorization: Bearer {{token}}

###
# posts.update
PUT {{BASE_URL}}/api/posts/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "body": "수정 맨 ~"
}

###
# posts.destroy
DELETE {{BASE_URL}}/api/posts/1
Content-Type: application/json
Authorization: Bearer {{token}}


###
# categories.index
GET {{BASE_URL}}/api/categories
?is_admin=true
Content-Type: application/json
Authorization: Bearer {{token}}


###
# categories.create
POST {{BASE_URL}}/api/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "parent_id": 4,
    "name": "임현진",
    "order": 1
}