# Generated by Django 3.1.4 on 2021-01-06 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('comments', '0001_initial'), ('comments', '0002_auto_20210104_0539'), ('comments', '0003_auto_20210104_0554'), ('comments', '0004_auto_20210104_0556'), ('comments', '0005_auto_20210104_0622'), ('comments', '0006_auto_20210106_0448')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentable_id', models.BigIntegerField()),
                ('commentable_type', models.CharField(max_length=75)),
                ('body', models.TextField()),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='삭제일')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['commentable_id', 'commentable_type', 'deleted_at'], name='comments_comment_f58a8d_idx'),
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_comment_f58a8d_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentable_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentable_type',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentable_id',
            field=models.PositiveIntegerField(db_column='commentable_id', default=None, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentable_type',
            field=models.ForeignKey(db_column='commentable_type', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='deleted_at'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['commentable_id', 'commentable_type', 'deleted_at'], name='comments_comment_f58a8d_idx'),
        ),
    ]
