# Generated by Django 3.1.4 on 2021-01-04 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_comment_f58a8d_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentable_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentable_type',
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
