# Generated by Django 3.1.4 on 2021-01-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20210104_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='object_id',
            new_name='commentable_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content_type',
            new_name='commentable_type',
        ),
    ]
