# Generated by Django 3.1.4 on 2021-01-13 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_squashed_0004_auto_20210113_0511'),
        ('authentication', '0002_auto_20210106_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.ForeignKey(db_constraint=False, default=None, limit_choices_to={'name': 'user_level'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.reference'),
        ),
    ]
