# Generated by Django 3.1.4 on 2021-01-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=100, verbose_name='level'),
        ),
        migrations.RunSQL('ALTER TABLE `users` MODIFY COLUMN `level` int NOT NULL AFTER `name`')
    ]
