# Generated by Django 3.1.4 on 2021-01-06 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachmentable_id', models.PositiveIntegerField(db_column='attachmentable_id', default=None, null=True)),
                ('attachmentable_type', models.ForeignKey(db_column='attachmentable_type', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='deleted_at')),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['attachmentable_id', 'attachmentable_type', 'deleted_at'], name='attachments_attachm_3a7ce1_idx'),
        ),
    ]
