# Generated by Django 3.1.4 on 2021-01-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('references', '0001_initial'), ('references', '0002_auto_20210113_0504'), ('references', '0003_auto_20210113_0507'), ('references', '0004_auto_20210113_0511')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='그룹 네임', max_length=75, verbose_name='name')),
                ('key', models.CharField(max_length=75, verbose_name='key')),
                ('value', models.CharField(max_length=75, verbose_name='value')),
                ('order', models.IntegerField(default=0, help_text='100 단위씩 끊어서 그룹화', verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'references',
                'ordering': ['name', 'order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['name'], name='references_name_ba7d79_idx'),
        ),
        migrations.AddConstraint(
            model_name='reference',
            constraint=models.UniqueConstraint(fields=('name', 'key', 'value'), name='unique_columns'),
        ),
    ]
